[project]
name = "chat_api"
version = "0.1.0"
description = "chat_api using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.9.3"
]

[project.scripts]
chat_api = "chat_api.main:run"
run_crew = "chat_api.main:run"
train = "chat_api.main:train"
replay = "chat_api.main:replay"
test = "chat_api.main:test"
run_with_trigger = "chat_api.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
